### ISSUE TITLE
Icons not displaying with cmder on Windows

### ISSUE THREAD

**Issue by adrianochs** [dlvhdr/gh-prs#21]
The nice icons you show in your gif of the `Readme` do not display when using cmder on Windows. Are you aware of any work-arounds?

**Comment by dlvhdr** [comment]
Hmm can you try installing a nerd font and changing the font of cmdr to it?

**Comment by adrianochs** [comment]
Thanks for your swift reply. That was it. Works like a charm now. Thanks again for your fantastic extension!
