### ISSUE TITLE
Support windows-amd64

### ISSUE THREAD

**Issue by Manish0925** [dlvhdr/gh-prs#26]
No support for windows

**Comment by abdfnx** [comment]
try install it manually

```bash
gh repo clone dlvhdr/gh-prs

cd gh-prs

gh extension install .
```

**Comment by younger-1** [comment]
Can config file use path like this `~/AppData/Roaming/prs/sections.yml` ?

**Comment by dlvhdr** [comment]
@younger-1  try setting the env variable `XDG_CONFIG_HOME`
