### ISSUE TITLE
[feature request] support refresh key

### ISSUE THREAD

**Issue by micalevisk** [dlvhdr/gh-prs#31]
What you think of adding another key to let users refreshes manually the section they have in focus? Maybe <kbd>r</kbd> right below the <kbd>o</kbd> one

![image](https://user-images.githubusercontent.com/13461315/145751197-e3676a77-a62a-4a09-b3eb-f2af04378bd9.png)

I know gh commands are in general one-time commands tho. But I think this feature can be handy as we can leave the results open while reading to the pull request at github.com and then we can go back to the terminal and just press `r` to fetch updates on the current section.

**Comment by dlvhdr** [comment]
https://github.com/dlvhdr/gh-prs/pull/52 closes
