### ISSUE TITLE
[BUG] items hidden by the terminal window can't be seen on the list view

### ISSUE THREAD

**Issue by micalevisk** [dlvhdr/gh-prs#61]
**Describe the bug**

We can't scroll down the viewport

**To Reproduce**

You just need to resize the window enough to hide some item

https://user-images.githubusercontent.com/13461315/148714370-90451dcb-f1cf-499c-9486-5ee248d2d00c.mp4

**Expected behavior**

somehow, the scroll should work.

**Desktop (please complete the following information):**
 - OS: ubuntu
 - extension version 2.0.0

**Comment by dlvhdr** [comment]
Thanks will fix. I think I know what caused this.
