### ISSUE TITLE
[BUG] Subscribed list is scoped to this repo and cli/cli

### ISSUE THREAD

**Issue by privatenumber** [dlvhdr/gh-prs#74]
**Describe the bug**
The "Subscribed" tab doesn't show anything relevant to me.

Looks like the Filter for it is scoped to `cli/cli` and this repository:
https://github.com/dlvhdr/gh-prs/blob/9f9aedad3bd392f990d96b722d4aff9fb893eaac/config/parser.go#L64

**Expected behavior**
To show issues/PRs that I'm subscribed to.

**Comment by dlvhdr** [comment]
Hi, the subscribed tab is just provided as an example. 
You're free to change the config however you want.

**Comment by micalevisk** [comment]
@privatenumber this is just the default config that will be used if you didn't have write your own [`config.yml`](https://github.com/dlvhdr/gh-prs#configuring). You should edit this file

**Comment by privatenumber** [comment]
Gotcha. Thanks for explaining.

I guess the feedback is that it was a confusing experience then.

I would probably want more useful/relevant defaults but feel free to close this.

**Comment by dlvhdr** [comment]
I'll try and think of better defaults
