### ISSUE TITLE
Support windows-amd64

### ISSUE THREAD

**Issue by abdfnx** [dlvhdr/gh-prs#9]
can you add support for `windows` ?

**Comment by dlvhdr** [comment]
hey, I added a github action that should take care of publishing the windows-amd64 exe
If you go to the releases page you can see the exe: https://github.com/dlvhdr/gh-prs/releases/tag/v1.1.1
Let me know if it doesn't work for another reason as I don't have a windows machine

**Comment by abdfnx** [comment]
ok, I will try it

**Comment by abdfnx** [comment]
yes, it's works, amazing

**Comment by abdfnx** [comment]
but

if I want to install it, I have to do a few steps

```
wget URL_TO_WINDOWS_AMD_FILE
# then I have to write `sections.yml` file at C:\Users\USERPROFILE\AppData\Roaming\prs
and writing my configs
```

so, maybe we have to create a new repo of `gh-prs` for windows, and name it `gh-prs-w` or something like this...

to make windows user can install this extension in one command

```
gh extension install dlvhdr/gh-prs-w
```

**Comment by abdfnx** [comment]
fixed

**Comment by muratmirgun** [comment]
Hey Bro maybe you can use Go Releaser :)
You can check from [https://goreleaser.com/](here)

**Comment by abdfnx** [comment]
> Hey Bro maybe you can use Go Releaser :) You can check from [https://goreleaser.com/](here)

I used `GoReleaser` for many project, and also for this project, but it's build `.zip` files

and we want executable files, but Thank you for your participation @muratmirgun

**Comment by seachicken** [comment]
> but
> 
> if I want to install it, I have to do a few steps
> 
> ```powershell
> wget URL_TO_WINDOWS_AMD_FILE
> mv ./windows-amd64.exe PATH
> [System.Environment]::SetEnvironmentVariable("Path", $Env:Path + ";GH_PRS_PATH", [System.EnvironmentVariableTarget]::User)
> 
> # then I have to write `sections.yml` file at C:\Users\USERPROFILE\AppData\Roaming\prs
> # and writing my configs
> ```
> 
> I will make a executable file

Maybe in the next release of cli/cli, we will be able to install it from the gh install command
https://github.com/cli/cli/pull/4717

**Comment by abdfnx** [comment]
after @dlvhdr merge #11 , all issues will be fixed

**Comment by abdfnx** [comment]
done
